[[headers]]
  for = "/*"
  [headers.values]
    Report-To = '''{"group":"default","max_age":31536000,"endpoints":[{"url":"https://gsferreira.report-uri.com/a/d/g"}],"include_subdomains":true}'''
    NEL = '''{"report_to":"default","max_age":31536000,"include_subdomains":true}'''


[[redirects]]
  from = "/rss.xml"
  to = "/feed.xml"
  status = 301
  force = true